name: Prueba de GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install || echo "No hay package.json, omitiendo instalación"

      - name: Ejecutar test de prueba
        run: echo "¡Prueba ejecutada con éxito!"

